openSUSE/hwinfo

- src/hd/sys.c
There is a new PowerPC platform PowerNV
Signed-off-by: Dinar Valeev <dvaleev@suse.com>
> Add PowerNV platform support

- src/hd/block.c
The ioctl() seems to block on some devices and recent kernels provide the data via sysfs already.
So we fetch it from sysfs if it's available there.
> scsi serial id: read vpd page 0x80 from sysfs, if possible (bsc #949287)

- src/hd/pci.c
The code actually creates two entries for each device: one is a pci device
and the other a virtio device. We want only the second because only this has
the interesting attributes like interface, mac address, or can be directly
linked to underlying block devices.
The patch keeps both entries internally but tags the pci device as having an
'unknown' device class effectively preventing it from showing up in any
device listing.
> avoid bogus virtio devices in device listing (bsc #960507)

- src/hd/usb.c
The link to input devices has been moved one level deeper into the sysfs tree
for usb devices.
> fix input device name detection for usb devices (bsc #989633)

- src/hd/hd.h
- src/hd/pci.c
- src/ids/src/bus
Basically we have to create a 'storage controller' where we can attach the
individual disk devices to.
> implement nvdimm support (bsc #970111)

- src/ids/convert_hd
- src/ids/src/pci
- src/ids/src/usb
Not much to review actually. Just a new set of ids downloaded from the respective web pages.
> update pci and usb ids (bsc #1006818)

- git2log
- src/hd/bios.c
- src/hd/hd.c
- src/hd/hd_int.h
This is a backport with slight adjustments of
- https://github.com/openSUSE/hwinfo/pull/41
- https://github.com/openSUSE/hwinfo/pull/42
> look for smbios entry point also in efi settings and sysfs (bsc#1010276)

- src/hd/pci.c
We just need to make it aware of the 'vnic' card type.
> powerpc: support ibmvnic network interfaces (bsc #1031676)

- Makefile
- src/ids/src/pci
- src/ids/src/usb
This pr
- updates the ids
- fixes a small packaging bug
> update pci and usb ids (fate #321448) 

- src/hd/mdt.c
There shouldn't be any real i/o needed for the BIOS to provide the list of
supported video modes. With this, the BIOS hopefully won't do any harm
anymore.
> block i/o access when reading mode list from BIOS (bsc #1033832)

- src/hd/bios.c
SMBIOS 3.0 defines a new header allowing the DMI records to be at any 64 bit
address. Also, it not longer contains the number of records.
For details, see:
http://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.1.1.pdf
section 5.2.2 (SMBIOS 3.0 (64-bit) Entry Point).
> support SMBIOS 3.0 spec (bsc #1062562)

- src/hd/pci.c
Match directly the known usb storage platform driver names. This should be
good until usb 4.0 comes along, I hope.
> try a more agressive way to catch all usb platform controllers (bsc #1072450)

- src/hd/sys.c
The purpose if this extra check is to minimize chances the vmware check will
have negative side effects.
> check for vmware only when running in a vm (bsc #1105003)

- src/hd/pci.c
This commit adds a new method called hd_read_visorbus
to read the hardware information from the new path:
/sys/bus/visorbus/devices
Signed-off-by: Jürgen Löhel <jloehel@suse.com>
> The location of the S-Par drivers virtual buses has changed

- src/hd/hd.c
Add loongarch architecture support
> recognize loongarch64 architecture

- src/hd/block.c
hwinfo --cdrom can close the open tray, correct it
> Donot close the open tray after read.

- src/hd/block.c
https://github.com/openSUSE/hwinfo/pull/108 had some issues; fix them.
> fix logic around cdrom detection

- src/hd/block.c
- https://bugzilla.suse.com/show_bug.cgi?id=1199948
`hwinfo --disk` output shows that disk is not attached to any nvme pci controller.
The offending drives set the CMIC value to non-zero, causing it to be recognized as a multipath device.
When `nvme_core.multipath=1` the device link in the SysFS's namespace entry points to nvme-subsys# and that causes some missing information, specificaly about PCI and namespace's parent device.
Here we go through the parent device withihn the nvme-subsys to gather complete information, and making the output's  ompatible to the previously seen.
Signed-off-by: Mauro S. M. Rodrigues <maurosr@linux.vnet.ibm.com>
> Keep NVMe's namespace output consistency when nvme_core.multipath=1 (bsc#1199948)

- src/hd/int.c
- src/hd/pci.c
- https://bugzilla.suse.com/show_bug.cgi?id=1240648
SoC network device detection on aarch64 (Raspberry Pi) did not work correctly.
New code tested on RPi 3 and 4.
> fix network card detection on aarch64 (bsc#1240648)

- src/hd/cpu.c
- src/hd/hd.c
- src/hd/hd.h
- src/hd/hdp.c
- provide more cpu info data
This uses https://github.com/openSUSE/hwinfo/pull/145 and fixes some issues with that pull request.
> capture more x86 fields from /proc/cpuinfo

- src/hd/hd.h
- src/ids/src/class
Add touchpad class in anticipation of https://github.com/openSUSE/hwinfo/pull/139.
> add touchpad class (bsc#1241295)

- src/hd/cpu.c
Fix minor issues with aarch64 cpu detection.
> fix aarch64 cpu detection (bsc#1241295)

- src/hd/hd.h
- src/hd/usb.c
> USB improvements
